- .github/ISSUE_TEMPLATE/issue--🌟feature.md
- .github/ISSUE_TEMPLATE/issue--🐞bugfix.md
- .github/ISSUE_TEMPLATE/issue--💯test.md
- .gitignore
- package-lock.json
- package.json
- public/index.html
- src/index.js
- src/raid/RaidMap.jsx
🌟(#2) [Feat] 레이드리스트 kakao map api 연결
-
✍️내용
-
kakao map api 연결 후 지도 출력
현재 좌표 지도에 마커로 출력
> 🌟(#2) [Feat] 레이드리스트 kakao map api 연결

- package-lock.json
- src/asset/css/LoadingSpinner.css
- src/asset/css/StampBoard.css
- src/asset/css/ThemeResultPage.css
- src/asset/css/bucketList.css
- src/asset/js/api.js
- src/component/theme/LoadingSpinner.jsx
- src/component/theme/StampBoard.jsx
- src/component/theme/ThemeAnalyzeResult.jsx
- src/component/theme/ThemeBucketList.jsx
- src/index.js
- 테마 대분류 추천페이지 + 소분류 추천 값 불러오는 것까지 구현
- 스탬프 보드 디자인
> 🌟(#12) 테마 대분류 추천페이지 제작 및 스탬프 보드 일부 디자인

- src/asset/css/cardlist.css
- src/asset/css/cardusagehistory.css
- src/component/card/CardList.jsx
- src/component/card/CardUsageHistory.jsx
> 🌟(#5) [Feat][Fix] 결제내역

- src/asset/css/raidBattle.css
- src/component/raid/RaidBattle.jsx
- src/index.js
> 🌟(#13) [Feat] 레이드 화면 체력 바와 공격  로그 풀링 구현

- src/asset/css/cardlist.css
- src/asset/css/cardusagehistory.css
- src/component/card/CardList.jsx
- src/component/card/CardUsageHistory.jsx
- src/component/common/PanelControl.jsx
- src/index.js
- 카드사용내역 css간단수정, 카드목록 카드이미지 s3링크로 수정
> 🌟(#5) [Fix] 카드사용내역, 카드목록

- src/component/point/PointMain.jsx
- src/component/point/PointTransfer.jsx
- src/component/point/TransferComplete.jsx
> 🌟(#4) [Feat] 포인트 페이지 DB 연결

- src/component/auth/Login.jsx
- src/component/common/Home.jsx
- src/component/common/NavBar.jsx
> 🌟(#1) 로그인 시 헤더변경및 메인화면 아이콘 경로 설정 

- src/asset/css/RaidHistory.css
- src/asset/css/style.css
- src/component/raid/HistoryCard.jsx
- src/component/raid/RaidHistory.jsx
> [Design] 레이드 참여내역 css 수정

- src/asset/css/raidBattle.css
- src/component/raid/RaidBattle.jsx
> [Feat][Fix] 레이드 정보 추가 및 디자인 수정

- src/asset/css/theme.css
- src/component/theme/MyThemeDetail.jsx
- src/component/theme/MyThemeSearch.jsx
- src/component/theme/ThemeDetail.jsx
- src/component/theme/ThemeSearchMain.jsx
- src/index.js
- 테마 검색기능 변경(키워드 검색버튼식 -> 실시간), 대주제 필터 클릭시 필터검색
- 테마 수정관련 CSS 구현 중
> 🌟(#6) [Feat] 테마 검색기능 및 필터검색  추가, 테마 수정기능 구현 중

- src/asset/css/cardlist.css
- src/asset/css/cardrecommend.css
- src/component/card/CardList.jsx
- src/component/card/CardRecommend.jsx
- src/component/common/PanelControl.jsx
- src/index.js
> 🌟(#5) 카드추천, 카드목록

- src/asset/css/ThemeResultPage.css
- src/component/theme/ThemeAnalyzeResult.jsx
- src/component/theme/ThemeRegister.jsx
- src/component/theme/ThemedBalloons.jsx
- 버킷리스트 결과 소분류 테마가 등록하기에 반영이 안되는 점 수정
- 추천 결과 페이지 디자인 수정
> 🌟(#12) [Fix] 버킷리스트 결과값 불러오기 오류 수정 및 추천결과 디자인 수정

- src/asset/css/theme.css
- src/component/theme/MyThemeDetail.jsx
- src/component/theme/ThemeDetail.jsx
- src/component/theme/ThemeRegister.jsx
- MyThemeDetail.jsx 페이지 구성 수정 (조회영역 일부 수정)
-
> 🌟(#6) [Feat][Fix] MyThemeDetail 페이지 수정기능 추가 및  수정

- src/component/card/CardUsageHistory.jsx
- src/index.js
> 🌟(#5) [Feat]세션

- src/component/raid/RaidBattle.jsx
> 🌟(#13 ) [Fix] 버프 정보 추가

- src/component/theme/MyThemeDetail.jsx
- src/component/theme/ThemeBucketList.jsx
- src/component/theme/ThemeRegister.jsx
-테마 수정 화면에서 기존 테마 불러오기 일부 수정
-
> 🌟(#12) [fix] 테마 수정 화면에서 기존 테마 불러오기 일부 수정

- src/component/theme/MyThemeDetail.jsx
- src/component/theme/ThemeRegister.jsx
> 🌟(#12) [fix] 테마 등록 최대 3개까지 가능 정책 추가

- src/asset/css/style.css
- src/component/common/NavBar.jsx
- src/component/common/PanelControl.jsx
> 🌟(#1) nav 수정 

- src/component/raid/RaidBattle.jsx
> 🌟(#13 ) [Fix] contribution 업데이트 로직 변경

- src/component/theme/ThemeBucketList.jsx
> 🌟(#12)[Fix] 버킷리스트 한글해석

- src/asset/css/carousel.css
- src/component/common/Home.jsx
- src/component/theme/ThemeList.jsx
> 🌟[Fix] 홈페이지 배너 수정

- src/App.js
- src/asset/css/nav.css
- src/component/common/NavBar.jsx
- src/component/common/PanelControl.jsx
- src/component/coupon/CouponMain.jsx
> 🌟(#4 ) [Fix] panelControl(sidebar) 수정

- src/asset/css/home.css
- src/asset/css/raidBattle.css
> [Fix] 내정보 글자 색 수정

- Dockerfile
- conf/conf.d/default.conf
> 🌟[Feat] Dockerfile & nginx 설정파일 추가

- .github/workflows/docker-image.yml
> 🌟[Feat] Create docker-image.yml

- src/asset/css/style.css
- src/index.js
> 🌟(#1) [Feat] Page Auth

- .github/workflows/docker-image.yml
> 🌟[Fix]Update docker-image.yml

- src/index.js
> 🌟(#1) 회원가입 창 인증 오류 수정

- .github/workflows/docker-image.yml
> 🌟[Fix] git action 조건

- src/asset/css/theme.css
- src/component/theme/ThemeSearchMain.jsx
- themeSearchMain.jsx (전체 테마 조회 페이지) 페이지네이션 버튼 로직 수정 (10페이지씩 나오게, 10페이지씩 건너뛰기)
- 끝버튼 클릭 시 유효하지 않은 버튼이 나오는 현상 발생으로 추가 수정 중
> 🌟(#6) [Fix] pagination 버튼 수정 (추가수정 아직 더 필요)

- conf/conf.d/default.conf
> 🌟[Feat] domain sever 설정

- src/asset/css/cardlist.css
- src/asset/css/cardusagehistory.css
- src/component/card/CardList.jsx
- src/component/card/CardRecommend.jsx
- src/component/card/CardUsageHistory.jsx
> 🌟(#5) [Feat]카드목록, 사용내역 css 수정

- src/component/card/CardUsageHistory.jsx
> 🌟(#5) [Fix] 카드사용내역 내림차순정렬 수정
